{
 "title": "Zamam",
 "time": { "from": "2024-12-06T15:50:00.000Z", "to": "2024-12-06T17:10:59.000Z" },
 "panels": [
  {
   "title": "Average AC Energy Consumption per Zone",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"z1_AC2(kW)\") AS \"Avg_z1_AC(kW)\",\n       mean(\"z2_AC1(kW)\") AS \"Avg_z2_AC(kW)\",\n       mean(\"z3_AC1(kW)\") AS \"Avg_z3_AC(kW)\",\n       mean(\"z4_AC1(kW)\") AS \"Avg_z4_AC(kW)\",\n       mean(\"z5_AC1(kW)\") AS \"Avg_z5_AC(kW)\")\nFROM \"abnormal_data_kmeans\"\nWHERE time >= now() - 3d\nGROUP BY time(1m)"
    }
   ]
  },
  {
   "title": "Indoor Environmental Conditions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \n  Last  (\"z4_S1(RH%)\") AS \"Current Humidity (RH%)\", \n   Last (\"z4_S1(lux)\") AS \"Current Light Intensity (lux)\" \nFROM \"abnormal_data_kmeans\" \nWHERE time >= now() - 1d \nGROUP BY time(1h) \nFILL(null)"
    }
   ]
  },
  {
   "title": "Average Light Consumption per Zone (Last 24 hours)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "SELECT  mean(\"z1_Light(kW)\") AS \"Avg_z1_Light(kW)\",        mean(\"z2_Light(kW)\") AS \"Avg_z2_Light(kW)\",        mean(\"z3_Light(kW)\") AS \"Avg_z3_Light(kW)\",        mean(\"z4_Light(kW)\") AS \"Avg_z4_Light(kW)\",        mean(\"z5_Light(kW)\") AS \"Avg_z5_Light(kW)\" FROM \"abnormal_data_gmm\" WHERE time >= now() - 1d GROUP BY time(1m)"
    }
   ]
  }
 ]
}