{
 "title": "Detailed Feature Analysis2",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Total Energy Consumption by Zone (Winter)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"z1_energy_kW\") AS \"z1(kW)\", \n       sum(\"z2_energy_kW\") AS \"z2(kW)\", \n       sum(\"z3_energy_kW\") AS \"z3(kW)\", \n       sum(\"z4_energy_kW\") AS \"z4(kW)\", \n       sum(\"z5_energy_kW\") AS \"z5(kW)\" \nFROM \"aggregated_abnormal_data\" \nWHERE \"season\" = 'winter' AND time > now() - 1d\nGROUP BY time(5m)\n"
    }
   ]
  },
  {
   "title": "Average Energy Consumption per Zone over Time in Winter Season",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"z1_energy_kW\") AS \"z1_avg(kW)\", \n       mean(\"z2_energy_kW\") AS \"z2_avg(kW)\", \n       mean(\"z3_energy_kW\") AS \"z3_avg(kW)\", \n       mean(\"z4_energy_kW\") AS \"z4_avg(kW)\", \n       mean(\"z5_energy_kW\") AS \"z5_avg(kW)\"\nFROM \"aggregated_abnormal_data\"\nWHERE \"season\" = 'winter'\nGROUP BY time(5m)\n"
    }
   ]
  },
  {
   "title": "Abnormal Consumption Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "\nSELECT COUNT(\"prediction\") AS \"Abnormal Count\"\nFROM \"abnormal_data_isolation_forest2\"\nWHERE \"prediction\" = -1\nAND time >= now() - 80m\nGROUP BY time(1h)\n"
    }
   ]
  },
  {
   "title": "Energy Consumption Comparison (Normal vs Abnormal) per Zone",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \n    SUM(\"z1_AC2(kW)\") + SUM(\"z1_AC3(kW)\") + SUM(\"z1_Plug(kW)\") AS \"z1_norm(kW)\"\nFROM \"abnormal_data_isolation_forest\"\nWHERE \"prediction\" = 1  -- النورمال\nGROUP BY time(1m)\n"
    },
    {
     "query": "SELECT \n    SUM(\"z1_AC2(kW)\") + SUM(\"z1_AC3(kW)\") + SUM(\"z1_Plug(kW)\") AS \"z1_abnorm(kW)\"\nFROM \"abnormal_data_isolation_forest\"\nWHERE \"prediction\" = -1  -- الابنورمال\nGROUP BY time(1m)\n"
    },
    {
     "query": "SELECT \n    SUM(\"z2_AC1(kW)\") + SUM(\"z2_Light(kW)\") + SUM(\"z2_Plug(kW)\") AS \"z2_norm(kW)\"\nFROM \"abnormal_data_isolation_forest\"\nWHERE \"prediction\" = 1  -- النورمال\nGROUP BY time(1m)\n"
    },
    {
     "query": "SELECT \n    SUM(\"z2_AC1(kW)\") + SUM(\"z2_Light(kW)\") + SUM(\"z2_Plug(kW)\") AS \"z2_abnorm(kW)\"\nFROM \"abnormal_data_isolation_forest\"\nWHERE \"prediction\" = -1  -- الابنورمال\nGROUP BY time(1m)\n"
    },
    {
     "query": "SELECT \n    SUM(\"z3_Light(kW)\") + SUM(\"z3_Plug(kW)\") AS \"z3_norm(kW)\"\nFROM \"abnormal_data_isolation_forest\"\nWHERE \"prediction\" = 1  -- النورمال\nGROUP BY time(1m)\n"
    },
    {
     "query": "SELECT \n    SUM(\"z3_Light(kW)\") + SUM(\"z3_Plug(kW)\") AS \"z3_abnorm(kW)\"\nFROM \"abnormal_data_isolation_forest\"\nWHERE \"prediction\" = -1  -- الابنورمال\nGROUP BY time(1m)\n"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    SUM(\"z4_AC1(kW)\") + SUM(\"z4_Light(kW)\") + SUM(\"z4_Plug(kW)\") AS \"z4_norm(kW)\"\nFROM \"abnormal_data_isolation_forest\"\nWHERE \"prediction\" = 1  -- النورمال\nGROUP BY time(1m)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "SELECT \n    SUM(\"z4_AC1(kW)\") + SUM(\"z4_Light(kW)\") + SUM(\"z4_Plug(kW)\") AS \"z4_abnorm(kW)\"\nFROM \"abnormal_data_isolation_forest\"\nWHERE \"prediction\" = -1  -- الابنورمال\nGROUP BY time(1m)\n"
    },
    {
     "query": "SELECT \n    SUM(\"z5_AC1(kW)\") + SUM(\"z5_Light(kW)\") + SUM(\"z5_Plug(kW)\") AS \"z5_norm(kW)\"\nFROM \"abnormal_data_isolation_forest\"\nWHERE \"prediction\" = 1  -- النورمال\nGROUP BY time(1m)\n"
    },
    {
     "query": "SELECT \n    SUM(\"z5_AC1(kW)\") + SUM(\"z5_Light(kW)\") + SUM(\"z5_Plug(kW)\") AS \"z5_abnorm(kW)\"\nFROM \"abnormal_data_isolation_forest\"\nWHERE \"prediction\" = -1  -- الابنورمال\nGROUP BY time(1m)\n"
    }
   ]
  }
 ]
}